### ISSUE TITLE
documentation outdated?

### ISSUE THREAD

**Issue by henfri** [geraldhansen/certbot_dns_myonlineportal#1]
Hello,

Thanks for the plugin!
I fear, the documentation is outdated. This way, I got it to run:
`certbot certonly --no-self-upgrade --agree-tos --authenticator dns-myonlineportal --dns-myonlineportal-propagation-seconds 120 --dns-myonlineportal-credentials /etc/letsencrypt/.myonlineportal-credentials.ini ...`

and 

```
dns_myonlineportal_username = 
dns_myonlineportal_password = 
dns_myonlineportal_endpoint = https://myonlineportal.net/set-acmeroot@homeserver
```

Greetings,
Hendrik

**Comment by geraldhansen** [comment]
Yes - you are right. I fixed this.
